<%@ Page Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="AdminHome.aspx.cs"
    Inherits="COCGenerator.AdminHome" Title="Arthur J. Gallagher & Co (Aus) Limited - Certificate" %>

<%@ Register Src="Controls/ucMessanger.ascx" TagName="ucMessanger" TagPrefix="uc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="breadbg">
        <div style="float: left">
            <span class="headertext">Hello Admin!</span></div>
        <div style="float: right; background-color: Transparent">
            <asp:HyperLink ID="hplLogs" runat="server" ForeColor="White" style="vertical-align: bottom; font-variant:small-caps; margin-right: 5px" Text="logs" NavigateUrl="~/Logs.aspx">Logs</asp:HyperLink></div>
    </div>
    <div>
        <uc1:ucMessanger ID="ucMessanger1" runat="server" />
    </div>
    <div class="con">
        <div>
            <span class="SubHead">Associations: </span>
            <asp:Label ID="lblAssociationMessage" runat="server" Text="There are no associations defined." ForeColor="Red"
                Visible="False"></asp:Label>
            <asp:GridView ID="grvAssociation" runat="server" AutoGenerateColumns="False" DataKeyNames="AssociationID"
                CellPadding="4" OnDataBound="grvAssociation_DataBound" DataSourceID="ObjectDataSource4" 
                AutoGenerateDeleteButton="True" onrowdeleting="grvAssociation_RowDeleting">
                <RowStyle CssClass="DataGrid_Item" />
                <Columns>
                    <asp:TemplateField>
                    <ItemTemplate>
                        <asp:HyperLink ID="hplEdit" NavigateUrl='<%# "AssociationEdit.aspx?aid=" + Eval("AssociationID") %>' runat="server">Edit</asp:HyperLink>
                        </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center" />
                    </asp:TemplateField>
                    <asp:BoundField DataField="AssociationID" HeaderText="Association ID" Visible="False">
                        <ItemStyle HorizontalAlign="Center" />
                    </asp:BoundField>
                    <asp:TemplateField HeaderText="Logo">
                        <ItemTemplate>
                            <asp:Image ID="imgLogo" runat="server" ImageUrl='<%# "ImageHandler.ashx?aid=" + Eval("AssociationID") %>' />
                        </ItemTemplate>
                        <HeaderStyle HorizontalAlign="Center" />
                        <ItemStyle HorizontalAlign="Center"></ItemStyle>
                    </asp:TemplateField>
                    <asp:BoundField DataField="AssociationName" HeaderText="Name">
                        <HeaderStyle HorizontalAlign="Center" />
                        <ItemStyle HorizontalAlign="Center" />
                    </asp:BoundField>
                    <asp:TemplateField ItemStyle-HorizontalAlign="Center">
                        <ItemStyle HorizontalAlign="Center"></ItemStyle>
                         <ItemTemplate>
                            <asp:HyperLink ID="hplPresets" runat="server" NavigateUrl='<%# "AssociationPresets.aspx?aid=" + Eval("AssociationID") %>'
                                Text="Presets" />
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" />
                   </asp:TemplateField>
                    <asp:TemplateField ItemStyle-HorizontalAlign="Center">
                        <ItemTemplate>
                            <asp:HyperLink ID="hplInsureds" runat="server" Text="Insureds" NavigateUrl='<%# "AssociationInsureds.aspx?aid=" + Eval("AssociationID") %>' />
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center"></ItemStyle>
                    </asp:TemplateField>
                </Columns>
                <AlternatingRowStyle CssClass="DataGrid_AlternatingItem" />
            </asp:GridView>
            <table cellpadding="2px">
                <tr>
                    <td align="center">
                        <asp:LinkButton ID="btnAddAssociation" runat="server" Width="35px" 
                            OnClick="btnAddAssociation_Click">Add</asp:LinkButton>
                    </td>
                    <td>
                        <asp:FileUpload ID="fulAddLogo" runat="server" />
                    </td>
                    <td>
                        <asp:TextBox ID="txtAddAssociation" runat="server" Style="width: 290px" MaxLength="100"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;</td>
                    <td class="note">
                        &uarr;&nbsp;logo&nbsp;&uarr;</td>
                    <td class="note">
                        &uarr;&nbsp;name&nbsp;&uarr;</td>
                </tr>
            </table>
            <asp:ObjectDataSource ID="ObjectDataSource4" runat="server" SelectMethod="ListAssociations" TypeName="COCGenerator.BusinesObjects.bizAssociation">
            </asp:ObjectDataSource>
        </div>
        <br />
        <div>
            <div>
                <span class="SubHead">Time Zones: </span>
                <asp:Label ID="lblTimeZoneMessage" runat="server" Text="There are no time zones defined." ForeColor="Red"
                    Visible="False"></asp:Label>
                <br />
                <asp:GridView ID="grvTimeZone" runat="server" AutoGenerateColumns="False" DataSourceID="ObjectDataSource3"
                    DataKeyNames="TimeZoneName" CellPadding="4" OnDataBound="grvTimeZone_DataBound"
                    AutoGenerateDeleteButton="True" OnRowDeleting="grvTimeZone_RowDeleting">
                    <RowStyle CssClass="DataGrid_Item" />
                    <Columns>
                        <asp:BoundField DataField="TimeZoneName" HeaderText="Time Zone">
                            <ItemStyle HorizontalAlign="Center" />
                        </asp:BoundField>
                        <asp:BoundField DataField="TimeZoneName" Visible="False">
                            <HeaderStyle HorizontalAlign="Center" />
                            <ItemStyle HorizontalAlign="Center" />
                        </asp:BoundField>
                    </Columns>
                    <AlternatingRowStyle CssClass="DataGrid_AlternatingItem" />
                </asp:GridView>
                <table cellpadding="2px">
                    <tr>
                        <td align="center">
                            <asp:LinkButton ID="btnAddTZ" runat="server" OnClick="btnAddTZ_Click" Width="35px">Add</asp:LinkButton>
                        </td>
                        <td>
                            <asp:TextBox ID="txtAddTimeZone" runat="server" Style="width: 290px" MaxLength="100"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td class="note">
                            &uarr;&nbsp;time zone&uarr;&nbsp;</td>
                    </tr>
                </table>
                <asp:ObjectDataSource ID="ObjectDataSource3" runat="server" SelectMethod="ListTimeZones" TypeName="COCGenerator.BusinesObjects.bizTimeZone">
                    <UpdateParameters>
                        <asp:Parameter Name="NewTimeZoneName" Type="String" />
                        <asp:Parameter Name="TimeZoneName" Type="String" />
                    </UpdateParameters>
                </asp:ObjectDataSource>
            </div>
        </div>
    </div>
</asp:Content>
