<%@ Page Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="AssociationPresets.aspx.cs"
    Inherits="COCGenerator.AssociationPresets" Title="Arthur J. Gallagher & Co (Aus) Limited - Certificate" %>

<%@ Register Src="Controls/ucMessanger.ascx" TagName="ucMessanger" TagPrefix="uc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="breadbg">
        <span class="headertext">Association Presets</span>
    </div>
    <div>
        <uc1:ucMessanger ID="ucMessanger1" runat="server" />
    </div>
    <div class="con">
        <span class="SubHead">List of Presets for </span>
        <asp:Label ID="lblAssociation" CssClass="SubHead" runat="server"></asp:Label>
        <br />
        <asp:Label ID="lblPresetMessage" runat="server" 
            Text="There are no presets defined. Please add one." ForeColor="Red"
            Visible="False"></asp:Label>
        <asp:GridView ID="grvPresets" runat="server" AutoGenerateColumns="False" CellPadding="4" OnDataBound="grvPresets_DataBound"
            Font-Bold="False" DataSourceID="ObjectDataSource1" AutoGenerateDeleteButton="True" 
            DataKeyNames="PresetID" onrowdeleting="grvPresets_RowDeleting">
            <RowStyle CssClass="DataGrid_Item" />
            <Columns>
                <asp:TemplateField ItemStyle-HorizontalAlign="Center">
                    <ItemTemplate>
                        <asp:HyperLink ID="hplView" runat="server" Text="View" NavigateUrl='<%# "PresetView.aspx?pid=" + Eval("PresetID") %>' />
                    </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center"></ItemStyle>
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:HyperLink ID="hplEdit" runat="server" Text="Edit" NavigateUrl='<%# "PresetEdit.aspx?pid=" + Eval("PresetID") %>' />
                    </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center"></ItemStyle>
                </asp:TemplateField>
                <asp:BoundField DataField="PresetID" HeaderText="Preset ID">
                    <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="AssociationName" HeaderText="Association" Visible="False"></asp:BoundField>
                <asp:BoundField DataField="DocumentType" HeaderText="Document Type">
                    <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="TemplateName" HeaderText="Template Name"></asp:BoundField>
            </Columns>
            <HeaderStyle CssClass="DataGrid_Header" Font-Bold="False" />
            <AlternatingRowStyle CssClass="DataGrid_AlternatingItem" />
        </asp:GridView>
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="ListPresetsByAssociation" TypeName="COCGenerator.BusinesObjects.bizPreset">
            <SelectParameters>
                <asp:QueryStringParameter Name="AssociationID" QueryStringField="aid" Type="Int32" />
            </SelectParameters>
        </asp:ObjectDataSource>
        <table cellpadding="2px">
            <tr>
                <td align="center">
                    <asp:LinkButton ID="btnAddPreset" runat="server" Width="36px" OnClick="btnAddPreset_Click">Add</asp:LinkButton>
                </td>
                <td>
                    <asp:DropDownList ID="ddlAddDocumentType" runat="server">
                        <asp:ListItem>Certificate of Currency</asp:ListItem>
                        <asp:ListItem>Certificate of Currency 3rd Party</asp:ListItem>
                        <asp:ListItem>Confirmation of Insurance</asp:ListItem>
                    </asp:DropDownList>
                </td>
                <td>
                    <asp:FileUpload ID="fulAddTemplate" runat="server" />
                </td>
            </tr>
            <tr>
                <td align="center">
                    &nbsp;</td>
                <td class="note">
                    &uarr;&nbsp;document type&nbsp;&uarr;</td>
                <td class="note">
                    &uarr;&nbsp;template file&nbsp;&uarr;</td>
            </tr>
        </table>
        <asp:Button ID="btnBack" runat="server" Text="Back" PostBackUrl="~/AdminHome.aspx" />
    </div>
</asp:Content>
