<%@ Page Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="AssociationInsureds.aspx.cs"
    Inherits="COCGenerator.AssociationInsureds" Title="Arthur J. Gallagher & Co (Aus) Limited - Certificate" %>

<%@ Register src="Controls/ucMessanger.ascx" tagname="ucMessanger" tagprefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="breadbg">
        <span class="headertext">Association Insureds</span>
    </div>
    <div>
        <uc1:ucMessanger ID="ucMessanger1" runat="server" />
    </div>
    <div>
        <span class="SubHead">List of Insureds for </span>
        <asp:Label ID="lblAssociation" CssClass="SubHead" runat="server"></asp:Label>
        <br />
        <asp:Label ID="lblInsuredMessage" runat="server" Text="There are no Insureds defined. Please add one."
            ForeColor="Red" Visible="False"></asp:Label>
        <asp:GridView ID="grvInsureds" runat="server" AutoGenerateColumns="False" DataKeyNames="InsuredID" 
            CellPadding="4" DataSourceID="ObjectDataSource1" ondatabound="grvInsured_DataBound" 
            onrowdatabound="grvInsureds_RowDataBound" AutoGenerateDeleteButton="True" 
            onrowdeleting="grvInsureds_RowDeleting">
            <RowStyle CssClass="DataGrid_Item" />
            <Columns>
                <asp:TemplateField>
                <ItemTemplate>
                    <asp:HyperLink ID="hplView" NavigateUrl='<%# "InsuredView.aspx?iid=" + Eval("InsuredID") %>' runat="server">View</asp:HyperLink>
                </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center" />
                </asp:TemplateField>
                <asp:TemplateField>
                <ItemTemplate>
                    <asp:HyperLink ID="hplEdit" NavigateUrl='<%# "InsuredEdit.aspx?iid=" + Eval("InsuredID") %>' runat="server">Edit</asp:HyperLink>
                </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center" />
                </asp:TemplateField>
                <asp:BoundField DataField="InsuredID" HeaderText="Insured ID" Visible="False">
                </asp:BoundField>
                <asp:BoundField DataField="InsuredName" HeaderText="Name">
                    <HeaderStyle HorizontalAlign="Center" />
                    <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="AccountExecutive" HeaderText="Account Executive" >
                    <HeaderStyle HorizontalAlign="Center" />
                    <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Insurer" HeaderText="Insurer" >
                    <HeaderStyle HorizontalAlign="Center" />
                    <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
            </Columns>
            <AlternatingRowStyle CssClass="DataGrid_AlternatingItem" />
        </asp:GridView>
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" 
            SelectMethod="ListInsuredsByAssociation" TypeName="COCGenerator.BusinesObjects.bizInsured">
            <SelectParameters>
                <asp:QueryStringParameter Name="AssociationID" QueryStringField="aid" Type="Int32" />
            </SelectParameters>
        </asp:ObjectDataSource>
        <asp:Button ID="btnAdd" runat="server" PostBackUrl="~/InsuredAdd.aspx" Text="Add Insured" />
        <asp:Button ID="btnBack" runat="server" PostBackUrl="~/AdminHome.aspx" Text="Back" />
    </div>
</asp:Content>
